/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hitek_serialJNI_serialJNI */

#ifndef _Included_com_hitek_serialJNI_serialJNI
#define _Included_com_hitek_serialJNI_serialJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hitek_serialJNI_serialJNI
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_hitek_serialJNI_serialJNI_init
  (JNIEnv *, jobject);

/*
 * Class:     com_hitek_serialJNI_serialJNI
 * Method:    mainloop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hitek_serialJNI_serialJNI_mainloop
  (JNIEnv *, jobject);

/*
 * Class:     com_hitek_serialJNI_serialJNI
 * Method:    mdbusreadbyte
 * Signature: (III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_hitek_serialJNI_serialJNI_mdbusreadbyte
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_hitek_serialJNI_serialJNI
 * Method:    mdbusreadword
 * Signature: (III)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_hitek_serialJNI_serialJNI_mdbusreadword
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_hitek_serialJNI_serialJNI
 * Method:    mdbuswritebyte
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_hitek_serialJNI_serialJNI_mdbuswritebyte
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_hitek_serialJNI_serialJNI
 * Method:    mdbuswriteword
 * Signature: (I[SII)I
 */
JNIEXPORT jint JNICALL Java_com_hitek_serialJNI_serialJNI_mdbuswriteword
  (JNIEnv *, jobject, jint, jshortArray, jint, jint);

/*
 * Class:     com_hitek_serialJNI_serialJNI
 * Method:    mdbusreaddword
 * Signature: (III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_hitek_serialJNI_serialJNI_mdbusreaddword
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_hitek_serialJNI_serialJNI
 * Method:    mdbuswritedword
 * Signature: (I[III)I
 */
JNIEXPORT jint JNICALL Java_com_hitek_serialJNI_serialJNI_mdbuswritedword
  (JNIEnv *, jobject, jint, jintArray, jint, jint);

/*
 * Class:     com_hitek_serialJNI_serialJNI
 * Method:    mdbusreadreal
 * Signature: (III)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_hitek_serialJNI_serialJNI_mdbusreadreal
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_hitek_serialJNI_serialJNI
 * Method:    mdbuswritereal
 * Signature: (I[FII)I
 */
JNIEXPORT jint JNICALL Java_com_hitek_serialJNI_serialJNI_mdbuswritereal
  (JNIEnv *, jobject, jint, jfloatArray, jint, jint);

/*
 * Class:     com_hitek_serialJNI_serialJNI
 * Method:    destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hitek_serialJNI_serialJNI_destory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
